# Generated by Django 4.0.6 on 2022-08-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_brand_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('stock', models.CharField(choices=[('in', 'In Stock'), ('out', 'Out of Stock')], max_length=20)),
                ('labels', models.CharField(blank=True, choices=[('hot', 'hot'), ('sale', 'sale'), ('new', 'new'), ('', 'default')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
            ],
        ),
    ]
